import localFont from "next/font/local";
import "./globals.css";
import RestaurantHeader from "./components/Header";
import RestaurantWebsite from "./components/Footer";
import Providers from "./Providers";  // ⬅️ import wrapper

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <RestaurantHeader />
          {children}
          <RestaurantWebsite />
        </Providers>
      </body>
    </html>
  );
}
